name: Python CI/CD with Docker in ML Directory

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build Docker Image in ML Directory
      run: |
        cd machine-learning-client/ML
        docker build -t myapp:test .

    - name: Run Pytest in Docker in ML Directory
      run: |
        cd machine-learning-client/ML
        docker run --rm myapp:test pytest
        
  deployment-on-dockerHub:
    runs-on: ubuntu-latest

    steps: 
    - uses: actions/checkout@v3
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Deploy on Docker Hub
      uses: docker/build-push-action@v3
      with:
        context: ./machine-learning-client/ML
        file: ./machine-learning-client/ML/Dockerfile
        push: true
        tags: hyteve/dom-ml:latest







     
